config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'apartments#landing'

  resources :apartments do
    resources :images, only: [:new, :create, :destroy]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
        can :access, :rails_admin   # grant access to rails_admin
        can :dashboard              # grant access to the dashboard
        can :manage, :all
       else
        can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :user

  has_many :images
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :apartment
  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :apartment

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apartments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    # Following line makes your model fb-omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]


  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   # assuming the user model has a name
        user.picture = auth.info.image # assuming the user model has an image
        user.token = auth.credentials.token
        user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  def index
    @apartments = Apartment.all
  end

  def show
    @apartment = Apartment.find(params[:id])
    @image = @apartment.images.first.picture.url
  end

  def new
    if user_signed_in?
      @apartment = Apartment.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    :authenticate_user!
    user = current_user
    @apartment = user.apartments.create(apartment_params)
    redirect_to new_apartment_image_path(@apartment)
    UserMailer.newapt_email(user).deliver
  end

  def edit
    @apartment = Apartment.find(params[:id])
    if current_user.id != @apartment.user_id
      redirect_to apartment_path(@apartment)
    end
  end

  def update
    @apartment = Apartment.find(params[:id])
    if current_user.id == @apartment.user_id
      @apartment.update(apartment_params)
      redirect_to apartment_path(@apartment)
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @apartment = Apartment.find(params[:id])
    if current_user.id != @apartment.user_id
      redirect_to apartment_path(@apartment)
    end
    @apartment.destroy
    redirect_to apartments_path
  end

  private
  def apartment_params
    params.require(:apartment).permit(:title, :description, :city, :people)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_in) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_filter :authenticate_user!

  def create
    @booking = Booking.new(bookings_params)
    if Booking.available(@booking)
      @booking.save
      redirect_to apartment_path(@booking.apartment), notice: "Booked! An email confirmation has been sent to you and the owner."
    else
      redirect_to :back, notice: "This apartment is not avaiable for those dates!"
    end
  end

private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date, :apartment_id, :user_id)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
    @apartment = Apartment.find(params[:apartment_id])
    @image = Image.new
  end

  def create
    @apartment = Apartment.find(params[:apartment_id])
    @image = @apartment.images.create(image_params)
    redirect_to new_apartment_image_path
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to apartments_path
  end

  private
  def image_params
    params.require(:image).permit(:apartment_id, :picture)
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apartments/_form.html.erb
<%= form_for @apartment, html: { multipart: true } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :people %>
  <%= f.text_field :people %>

  <%= f.submit %>
<% end %>

app/views/apartments/_search_form.html.erb
<form class="form-inline" role="form">
  <div class="form-group">
    <label class="sr-only" for="city">City</label>
    <input type="city" class="form-control" id="citysearch" placeholder="Enter the city">
  </div>
  <div class="form-group">
    <label class="sr-only" for="people">City</label>
    <input type="people" class="form-control" id="people" placeholder="How many people ?">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>

app/views/apartments/edit.html.erb
<%= render 'form' %>

app/views/apartments/index.html.erb
<h1 class="text-center">List of apartments</h1>


<div class="container">
  <div class="row">
    <% @apartments.each do |apartment| %>

      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">

          <%= image_tag apartment.images.first.picture.url(:medium) %>

          <div class="caption">
            <h3>Title: <%= apartment.title %></h3>
            <h4>City: <%= apartment.city %></h4>
            <h5>NAME OF THE FLAT</h5>
            <p></p>
            <p><%= link_to 'More...', apartment_path(apartment), class: "btn" %></p>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/apartments/landing.html.erb
<div class="wrapper">

    <h1 class="text-center">Find your bed anywhere</h1>

    <h2 class="text-center">In the nearest cities</h2>

    <div class="search-bar text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <%= render 'search_form' %>
          </div>
        </div>
      </div>
    </div>

</div>

<div class="container">

  <p>News</p>

  <p>News</p>

  <p>News</p>

</div>

app/views/apartments/new.html.erb
<%= render 'form' %>

app/views/apartments/show.html.erb
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!--
      Indicators  <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
     -->

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <% @apartment.images.each_with_index do |image, i| %>
        <div class="item <%= i.zero? ? 'active' : '' %>">
          <%= image_tag image.picture.url %>
        </div>
      <% end %>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
  </div>
</div>



<div class="text-center">

  <h1><%= @apartment.title %></h1>

  Description : <h3><%= @apartment.description %></h3>

  City : <h3><%= @apartment.city %></h3>

  People : <h3><%= @apartment.people %></h3>

  <%= link_to 'Back', apartments_path, class: "btn btn-primary" %>

  <% if user_signed_in? %>
    <% if current_user.id == @apartment.user_id %>
      <%= link_to 'Edit', edit_apartment_path(@apartment), class: "btn btn-warning" %>
      <%= link_to 'Delete', apartment_path(@apartment), method: :delete, class: "btn btn-danger" %>
    <% end %>
  <% end %>

</div>

app/views/images/new.html.erb
<h3 class="text-center vertical-margin-s">Add pictures from your flat</h3>

<ul class="list-inline text-center vertical-margin-s"><% @apartment.images.each do |image| %>
  <li><%= image_tag image.picture.url(:medium) %></li>
  <% end %>
</ul>

<div class="row">
  <div class="col-sm-offset-4 col-sm-4 ">
    <div class="text-center vertical-margin-s">

      <%= form_for [@apartment, @image], html: { multipart: true } do |f| %>

        <%= f.file_field :picture, :class => 'vertical-margin-s' %>

        <%= f.submit 'Upload image', :class => 'btn' %>

      <% end %>

    </div>
  </div>
</div>

<%= link_to 'Finish', apartment_path(@apartment), class: "btn btn-success btn-done" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a>Airbed</a>
    by Le Wagon
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a>
        <%= link_to 'AIRBED', root_path, class: "navbar-brand" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to 'Add your own flat', new_apartment_path %>
        </li>
      </ul>

      <div class="nav navbar-nav navbar-right">
        <ul class="list-inline">
          <li><%= render 'layouts/sessions' %></li>
        </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sessions.html.erb
<% if user_signed_in? %>
  <%= current_user.username %>
  <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', :class => 'btn btn-default' %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path, :class => 'btn btn-default' %>
  <%= link_to 'Sign in', new_user_session_path, :class => 'btn btn-default' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbed</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</html>